version: '3.3'

services:
  simple-ci-cd:
    entrypoint: 
      - node 
      - /project/scripts/dev_start.js
    image: node:latest
    ports:
      - 3322:3322
    volumes:
      - "../:/project"